# Generated by Django 5.0.1 on 2024-03-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=100)),
                ('Shm', models.CharField(max_length=100)),
                ('Sloc', models.CharField(max_length=100)),
            ],
        ),
    ]
